/** @type {import('tailwindcss').Config} */
// Clinical Clarity design tokens (from reference_design_image/clinical_clarity/DESIGN.md).
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'tertiary-fixed-dim': '#4ae176',
        'inverse-on-surface': '#eaf1ff',
        surface: '#f8f9ff',
        'tertiary-fixed': '#6bff8f',
        'surface-bright': '#f8f9ff',
        'on-tertiary-container': '#f7fff3',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-background': '#0b1c30',
        'primary-container': '#6063ee',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        'on-secondary-container': '#fefcff',
        'error-container': '#ffdad6',
        tertiary: '#006b2d',
        secondary: '#0058be',
        'secondary-container': '#2170e4',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'on-surface-variant': '#464554',
        'surface-tint': '#494bd6',
        'surface-variant': '#d3e4fe',
        'on-primary': '#ffffff',
        'on-tertiary-fixed': '#002109',
        'on-tertiary-fixed-variant': '#005321',
        'on-error-container': '#93000a',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-error': '#ffffff',
        'inverse-primary': '#c0c1ff',
        primary: '#4648d4',
        'on-primary-container': '#fffbff',
        'tertiary-container': '#00873b',
        'inverse-surface': '#213145',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        error: '#ba1a1a',
        'on-surface': '#0b1c30',
        background: '#f8f9ff',
        // Warm amber for the "Sedang / Perlu Observasi" middle risk band.
        warning: '#b45309',
        'warning-container': '#fef3c7',
        'on-warning-container': '#92400e',
      },
      borderRadius: {
        DEFAULT: '0.5rem', // 8px base per design system
        md: '0.75rem',
        lg: '1rem',
        xl: '0.75rem', // cards use rounded-xl == 12px in the reference markup
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        base: '8px',
        sm: '12px',
        md: '24px',
        lg: '32px',
        xl: '48px',
        gutter: '24px',
      },
      maxWidth: {
        'container-max': '1280px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
